USE [master]
GO

/****** Object:  Database [RemoteLogger]    Script Date: 3/23/2022 3:37:02 PM ******/
CREATE DATABASE [RemoteLogger]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RemoteLogger', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RemoteLogger.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RemoteLogger_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RemoteLogger_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RemoteLogger].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RemoteLogger] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RemoteLogger] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RemoteLogger] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RemoteLogger] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RemoteLogger] SET ARITHABORT OFF 
GO

ALTER DATABASE [RemoteLogger] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RemoteLogger] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RemoteLogger] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RemoteLogger] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RemoteLogger] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RemoteLogger] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RemoteLogger] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RemoteLogger] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RemoteLogger] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RemoteLogger] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RemoteLogger] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RemoteLogger] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RemoteLogger] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RemoteLogger] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RemoteLogger] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RemoteLogger] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RemoteLogger] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RemoteLogger] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RemoteLogger] SET  MULTI_USER 
GO

ALTER DATABASE [RemoteLogger] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RemoteLogger] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RemoteLogger] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RemoteLogger] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RemoteLogger] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RemoteLogger] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RemoteLogger] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RemoteLogger] SET  READ_WRITE 
GO

